% This is a demo used to demonstrate how to use computeNonParaEMFixed and 
% display the progress trajectory of biomarkers
[x,fval,ppcell_mu,stdY,ageonset,thetaMu,beta,t_cn_mci,ADage,...
    e_cn,e_ad,D_ad,D_cn,Y_ad_diff,Y_cn_diff] = ...
    computeNonParaEMFixed(ptTable,hcTable,IDName,AgeName,DiagName,...
    DemoNames,featureNames,isMRI,w,knots,lambda,rho);
figure
set(gcf, 'Units', 'centimeters', 'Position', [10 10 18 20]); % Set figure size
titleList = {'Centiloid','AV1451 PET SUVR of Braak 1/2 ROI',...
        'AV1451 PET SUVR of Braak 3/4 ROI','AV1451 PET SUVR of Braak 5/6 ROI',...
        'Hippocampal volume','Middle temporal gyrus volume','Fusiform gyrus volume','Amygdala volume',...
        'CDR-SB','MMSE','FAQ','LM-Delayed'};
YtitleList = {'Centilold difference from control','SUVR difference from control',...
        'SUVR difference from control','SUVR difference from control',...
        'Volume difference from control (mm^{3})','Volume difference from control (mm^{3})',...
        'Volume difference from control (mm^{3})','Volume difference from control (mm^{3})',...
        'Score difference from control', 'Score difference from control', 'Score difference from control',...
        'Score difference from control'};
fea = 1:12;
for i=1:length(fea)
    axi = nexttile;
    plot(axi,-20:10,fnval(ppcell_mu{i},-20:10),'Color',[0 0.4470 0.7410],'LineWidth',3);
    title(axi,titleList{i},'Units','normalized','Position',[0.5,1.01]);
    ylabel(axi,YtitleList{i});
    set(axi, 'FontSize', 6, 'FontName', 'Helvetica'); % Set axis font size and type
end
